version: '2'
services:
    nginx:
        image: nginx:stable-alpine
        volumes:
            - /var/vhost/xor.dev:/var/vhost/xor.dev
            - ./conf.template:/etc/nginx/conf.d/conf.template
        ports:
            - "80:80"
        depends_on:
            - php
        env_file: environment.env
        environment:
            PROJECT_PATH: /var/vhost/xor.dev
        command: /bin/sh -c "envsubst '$$NGINX_HOST$$PROJECT_PATH' < /etc/nginx/conf.d/conf.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"
    php:
        build:
            context: ./php
            dockerfile: Dockerfile
            args:
                user: ${USER}
                project_path: /var/vhost/xor.dev
        volumes:
            - /var/vhost/xor.dev:/var/vhost/xor.dev
            - composer_volume:$HOME/.composer
            - composer_volume:/var/lib/composer
        depends_on:
            - db
        env_file: environment.env
        environment:
            XDEBUG_CONFIG: remote_host=172.17.0.1
            USER_NAME: ${USER}
            PROJECT_PATH: /var/vhost/xor.dev
    db:
        image: mysql
        ports:
            - "6001:3306"
        volumes:
            - ./db/:/tmp/db
        environment:
            - MYSQL_DATABASE=xor
            - MYSQL_USER=xor
            - MYSQL_PASSWORD=xor
            - MYSQL_ROOT_PASSWORD=xor
volumes:
    composer_volume:
        external: true
